import '@/styles/globals.css';
import type { Metadata } from 'next';

import { Header, Toast } from '@/components';
import { NextKBarProvider, NextThemesProvider } from '@/providers';
import { darkTheme, font, lightTheme } from '@/styles';

import * as styles from './layout.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko" className={font.className}>
      <body className={styles.container}>
        <NextKBarProvider>
          <NextThemesProvider
            storageKey="theme"
            attribute="class"
            value={{
              light: lightTheme,
              dark: darkTheme,
            }}
          >
            <Toast />
            <Header />
            <main>{children}</main>
          </NextThemesProvider>
        </NextKBarProvider>
      </body>
    </html>
  );
}
